Feature: ind App Globalization samps Automation 

Scenario: ind App Globalization samps Automation 

	Given Script opens browser and navigates to application 
	When Script logs into the application 
	Then Script clicks on menu and clicks on search preferences and select desired interface language and validtes text in homepage for the selected language 
	Then Script logouts from the application and closes the browser 
	
